export const ONBOARDING_STEPS = [
  { id: 0, label: "Processing Information", key: "processingInfo" },
  { id: 1, label: "Main Applicant Details", key: "mainApplicant" },
  { id: 2, label: "Current Address", key: "currentAddress" },
  { id: 3, label: "Contact Details", key: "contactDetails" },
  { id: 4, label: "Sponsor's Information", key: "sponsorInfo" },
  { id: 5, label: "Academic Information", key: "academicInfo" },
  { id: 6, label: "English Language Proficiency", key: "englishProficiency" },
  { id: 7, label: "Past Work Experiences", key: "workExperience" },
  { id: 8, label: "Dependent Information", key: "dependentInfo" },
  { id: 9, label: "Marital Status", key: "maritalStatus" },
  { id: 10, label: "Emergency Contact", key: "emergencyContact" },
  { id: 11, label: "Immigration History", key: "immigrationHistory" },
  { id: 12, label: "Visa", key: "visa" },
  { id: 13, label: "Visa Rejection", key: "visaRejection" },
  { id: 14, label: "Immigration Incident", key: "immigrationIncident" },
  { id: 15, label: "Criminal Records", key: "criminalRecords" },
  { id: 16, label: "Inadmissibility", key: "inadmissibility" },
  { id: 17, label: "Health", key: "health" },
];
